// Táboa de nomes do atlas, extraída do artefacto do 19.3 para non
// retecleala nin perder un acento. É a fonte de verdade do CONTIDO;
// a estrutura (que conecta con que) constrúea `atlas-fisterra.mjs`.
//
// Emítese como JSON a propósito: escapar apóstrofos a man xa me
// rompeu o ficheiro unha vez («Sailor's Knot»).

export const GRUPOS = [
  ['costa', 'A Costa', 'The Coast', '#3a6a7c'],
  ['monte', 'O Monte', 'The Hill', '#6b5a3a'],
  ['fraga', 'A Fraga', 'The Deep Wood', '#3f6b46'],
  ['mar', 'O Mar Aberto', 'The Open Sea', '#2f4f7a'],
  ['vila', 'A Vila', 'The Town', '#7a5a2f'],
  ['alen', 'O Alén', 'The Beyond', '#5a3a6b'],
]

export const TINTES = [
  ['costa', 'A Costa', '#3a6a7c'],
  ['monte', 'O Monte', '#6b5a3a'],
  ['fraga', 'A Fraga', '#3f6b46'],
  ['mar', 'O Mar Aberto', '#2f4f7a'],
  ['vila', 'A Vila', '#7a5a2f'],
  ['alen', 'O Alén', '#5a3a6b'],
]

/** [id, gl, en, icona, tipo, grupo] */
export const NODOS = [
  ['fisterra', 'Fisterra', 'Finisterre', 'norse-world-tree', 'root', ''],
  ['praia', 'A Praia', 'The Shore', 'norse-drakkar', 'notable', 'costa'],
  ['redes', 'Redes', 'Nets', 'logic-intersect', 'small', 'costa'],
  ['no', 'Nó Mariñeiro', "Sailor's Knot", 'logic-fork', 'small', 'costa'],
  ['remendo', 'O Remendo', 'The Mending', 'forge-weld', 'small', 'costa'],
  ['marisqueo', 'Marisqueo', 'Shellfishing', 'forge-cart', 'small', 'costa'],
  ['mareas', 'Ler as Mareas', 'Reading Tides', 'norse-moon', 'small', 'costa'],
  ['berberecho', 'O Berberecho', 'The Cockle', 'forge-plate', 'small', 'costa'],
  ['dorna', 'A Dorna', 'The Dorna', 'norse-drakkar', 'small', 'costa'],
  ['calafate', 'Calafate', 'Caulking', 'forge-weld', 'small', 'costa'],
  ['vela', 'Vela Latina', 'Lateen Sail', 'norse-rune-sowilo', 'small', 'costa'],
  ['faro', 'O Faro', 'The Lighthouse', 'norse-fire', 'small', 'costa'],
  ['sal', 'Sal Mariña', 'Sea Salt', 'norse-ice-crystal', 'small', 'costa'],
  ['percebe', 'O Percebe', 'The Barnacle', 'forge-rivet', 'small', 'costa'],
  ['ribeira', 'Mestre de Ribeira', 'Shipwright', 'forge-wrench', 'keystone', 'costa'],
  ['patron', 'Patrón de Baixura', 'Inshore Skipper', 'logic-compass', 'keystone', 'costa'],
  ['senor-costa', 'Señor da Costa', 'Lord of the Coast', 'norse-mead-horn', 'ascendancy', 'costa'],
  ['carreiro', 'O Carreiro', 'The Path', 'logic-map-marker', 'notable', 'monte'],
  ['pastoreo', 'Pastoreo', 'Herding', 'norse-leaf', 'small', 'monte'],
  ['curro', 'O Curro', 'The Roundup', 'forge-guard', 'small', 'monte'],
  ['bestas', 'As Bestas', 'The Wild Mares', 'norse-wolf', 'small', 'monte'],
  ['pedra-seca', 'Pedra Seca', 'Drystone', 'forge-wall', 'small', 'monte'],
  ['muro', 'O Muro', 'The Wall', 'forge-wall', 'small', 'monte'],
  ['cortello', 'O Cortello', 'The Fold', 'forge-shelf', 'small', 'monte'],
  ['toxo', 'Uz e Toxo', 'Heath and Gorse', 'norse-sprout', 'small', 'monte'],
  ['rozar', 'Rozar', 'Clearing', 'norse-axe', 'small', 'monte'],
  ['cinza', 'A Cinza', 'The Ash', 'norse-fire', 'small', 'monte'],
  ['mamoa', 'A Mámoa', 'The Barrow', 'norse-rune-algiz', 'small', 'monte'],
  ['neboa', 'A Néboa', 'The Fog', 'logic-eye-closed', 'small', 'monte'],
  ['aguia', 'A Aguia', 'The Eagle', 'norse-raven', 'small', 'monte'],
  ['saber-monte', 'Coñecer o Monte', 'Knowing the Hill', 'logic-scroll', 'keystone', 'monte'],
  ['home-pedra', 'Home de Pedra', 'Stone Wright', 'forge-mortar', 'keystone', 'monte'],
  [
    'senora-monte',
    'Señora do Monte',
    'Lady of the Hill',
    'norse-horned-helmet',
    'ascendancy',
    'monte',
  ],
  ['souto', 'O Souto', 'The Grove', 'norse-leaf', 'notable', 'fraga'],
  ['carballo', 'O Carballo', 'The Oak', 'norse-world-tree', 'small', 'fraga'],
  ['landra', 'A Landra', 'The Acorn', 'norse-sprout', 'small', 'fraga'],
  ['vara', 'A Vara', 'The Switch', 'logic-rune', 'small', 'fraga'],
  ['cogomelos', 'Cogomelos', 'Mushrooms', 'norse-sparkle', 'small', 'fraga'],
  ['herbas', 'Herbas', 'Herbs', 'norse-leaf', 'small', 'fraga'],
  ['unguento', 'O Ungüento', 'The Salve', 'forge-plate', 'small', 'fraga'],
  ['corza', 'A Corza', 'The Roe Deer', 'norse-wolf', 'small', 'fraga'],
  ['rastro', 'O Rastro', 'The Trail', 'logic-map-marker', 'small', 'fraga'],
  ['trampa', 'A Trampa', 'The Snare', 'forge-hook', 'small', 'fraga'],
  ['fento', 'O Fento', 'The Fern', 'norse-sprout', 'small', 'fraga'],
  ['musgo', 'O Musgo', 'The Moss', 'norse-leaf', 'small', 'fraga'],
  ['regato', 'O Regato', 'The Brook', 'norse-ice-crystal', 'small', 'fraga'],
  ['bosque-vello', 'Bosque Vello', 'The Old Wood', 'norse-world-tree', 'keystone', 'fraga'],
  ['man-herbas', 'Man de Herbas', 'Herb Hand', 'logic-seedling', 'keystone', 'fraga'],
  [
    'espirito-fraga',
    'Espírito da Fraga',
    'Spirit of the Wood',
    'norse-world-tree',
    'ascendancy',
    'fraga',
  ],
  ['barra', 'A Barra', 'The Bar', 'norse-serpent', 'notable', 'mar'],
  ['polar', 'A Estrela Polar', 'The Pole Star', 'logic-star', 'small', 'mar'],
  ['sonda', 'A Sonda', 'The Sounding', 'forge-weight', 'small', 'mar'],
  ['carta', 'A Carta', 'The Chart', 'logic-scroll', 'small', 'mar'],
  ['temporal', 'O Temporal', 'The Gale', 'norse-lightning', 'small', 'mar'],
  ['ancorar', 'Ancorar', 'Anchoring', 'forge-hook', 'small', 'mar'],
  ['capear', 'Capear', 'Riding it Out', 'forge-guard', 'small', 'mar'],
  ['cardume', 'O Cardume', 'The Shoal', 'logic-intersect', 'small', 'mar'],
  ['cerco', 'O Cerco', 'The Purse Seine', 'logic-gate', 'small', 'mar'],
  ['salgar', 'Salgar', 'Salting', 'norse-ice-crystal', 'small', 'mar'],
  ['illa', 'A Illa', 'The Island', 'norse-mountain', 'small', 'mar'],
  ['bruma', 'A Bruma', 'The Haze', 'logic-eye-closed', 'small', 'mar'],
  ['golfino', 'O Golfiño', 'The Dolphin', 'norse-serpent', 'small', 'mar'],
  ['navegante', 'Navegante', 'The Navigator', 'logic-compass', 'keystone', 'mar'],
  ['mestre-temporais', 'Mestre de Temporais', 'Storm Master', 'norse-lightning', 'keystone', 'mar'],
  ['dono-mar', 'Dono do Mar Aberto', 'Master of Open Sea', 'norse-triquetra', 'ascendancy', 'mar'],
  ['feira', 'A Feira', 'The Fair', 'forge-cart', 'notable', 'vila'],
  ['trocar', 'Trocar', 'Bartering', 'forge-link', 'small', 'vila'],
  ['peso', 'Peso e Medida', 'Weight and Measure', 'forge-weight', 'small', 'vila'],
  ['fiado', 'O Fiado', 'On Credit', 'forge-barcode', 'small', 'vila'],
  ['forxa', 'A Forxa', 'The Forge', 'norse-fire', 'small', 'vila'],
  ['ferradura', 'A Ferradura', 'The Horseshoe', 'forge-arc', 'small', 'vila'],
  ['aceiro', 'O Aceiro', 'The Steel', 'norse-sword', 'small', 'vila'],
  ['muino', 'O Muíño', 'The Mill', 'forge-nut', 'small', 'vila'],
  ['farina', 'A Fariña', 'The Flour', 'forge-plate', 'small', 'vila'],
  ['forno', 'O Forno', 'The Oven', 'norse-fire', 'small', 'vila'],
  ['taberna', 'A Taberna', 'The Tavern', 'norse-mead-horn', 'small', 'vila'],
  ['gaita', 'A Gaita', 'The Bagpipe', 'norse-mead-horn', 'small', 'vila'],
  ['romaria', 'A Romaría', 'The Pilgrimage', 'logic-map-marker', 'small', 'vila'],
  ['ferreiro', 'O Ferreiro', 'The Smith', 'forge-wrench', 'keystone', 'vila'],
  ['tratante', 'O Tratante', 'The Dealer', 'forge-nameplate', 'keystone', 'vila'],
  ['cabeza-vila', 'Cabeza da Vila', 'Head of the Town', 'forge-nameplate', 'ascendancy', 'vila'],
  ['cruceiro', 'O Cruceiro', 'The Wayside Cross', 'logic-cross', 'notable', 'alen'],
  ['compana', 'A Santa Compaña', 'The Holy Company', 'logic-forbidden', 'small', 'alen'],
  ['luz-animas', 'Luz de Ánimas', 'Corpse Light', 'norse-fire', 'small', 'alen'],
  ['non-mirar', 'Non Mirar', 'Not Looking', 'logic-eye-closed', 'small', 'alen'],
  ['meigallo', 'O Meigallo', 'The Hex', 'norse-rune-fehu', 'small', 'alen'],
  ['nomes', 'Coñecer Nomes', 'Knowing Names', 'logic-rune', 'small', 'alen'],
  ['desfacer', 'Desfacer', 'Undoing', 'logic-cross', 'small', 'alen'],
  ['fonte', 'A Fonte Santa', 'The Holy Spring', 'norse-ice-crystal', 'small', 'alen'],
  ['auga-marzo', 'Auga de Marzo', 'March Water', 'norse-moon', 'small', 'alen'],
  ['sinal', 'O Sinal', 'The Sign', 'norse-rune-tiwaz', 'small', 'alen'],
  ['corredoira', 'A Corredoira', 'The Hollow Way', 'logic-map-marker', 'small', 'alen'],
  ['medianoite', 'Media Noite', 'Midnight', 'norse-moon', 'small', 'alen'],
  ['silencio', 'O Silencio', 'Silence', 'logic-eye-closed', 'small', 'alen'],
  ['sabia', 'A Sabia', 'The Wise Woman', 'logic-crown', 'keystone', 'alen'],
  ['camino-torto', 'Camiño Torto', 'The Crooked Road', 'logic-fork', 'keystone', 'alen'],
  ['voz-alen', 'Voz do Alén', 'Voice of the Beyond', 'norse-odin-eye', 'ascendancy', 'alen'],
]
